all: subdirs

subdirs:
	for dir in $(DIRS); do \
          $(MAKE) -C $$dir; \
        done

clean:
	for dir in $(DIRS); do \
          $(MAKE) -C $$dir clean; \
        done

.PHONY: all clean subdirs
