CAMLDEP=ocamldep.opt
CAMLOPT=ocamlopt.opt

COMPFLAGS=-I ../../lib
LINKFLAGS=$(COMPFLAGS) bigarray.cmxa hdf5_caml.cmxa
SRC=$(wildcard *.ml)
TARGETS=$(SRC:.ml=.exe)

.SUFFIXES: .exe .ml .mli .cmi .cmx

all: $(TARGETS)

.ml.exe: ../../lib/hdf5_caml.cmxa
	$(CAMLOPT) $(LINKFLAGS) -o $@ $<

clean::
	rm -f *.cm* *.exe *.o core.*

depend:
	$(CAMLDEP) *.mli *.ml > .depend

run: $(TARGETS)
	@for i in $^; do ./$$i; done

.PHONY: all depend clean run

include .depend
