#define H5_USE_18_API 1
#include "hdf5.h"
#include "h5_stubs.h"
#include "h5d_stubs.h"
#include "h5i_stubs.h"
#include "h5l_stubs.h"
#include "h5p_stubs.h"
#include "h5o_stubs.h"
#include "h5r_stubs.h"
#include "h5s_stubs.h"
#include "h5t_stubs.h"
#include "h5z_stubs.h"
#include "hid_stubs.h"
